# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: What the FdA
email: awesomephant@gmail.com
description: Camberwell College of Arts FdA Graphic Design & Illustration Degree Show 2017
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wtfda.co.uk" # the base hostname & protocol for your site
twitter_username: wtfda_show
instagram_username:  wtfda_show

# Build settings
markdown: kramdown
